### ISSUE TITLE
inconsistency in _Data.js

### ISSUE THREAD

**Issue by dmh2000** [udacity/reactnd-project-would-you-rather-starter#1]
unless I misunderstand how it is supposed to work, there seems to be a consistency error in the _DATA.js file. the 'johndoe' user object has in answers   "6ni6ok3ym7mf1p33lnez": 'optionOne', indicating johndoe chose option one for this question. but in the question object for 6ni6ok3ym7mf1p33lnez, it lists 0 votes for optionOne, and lists johndoe as choosing optionTwo. Is this intentional or an error in the data? Or do i misunderstand the schema?

**Comment by maboud** [comment]
same issue with sarahedo and question 6ni6ok3ym7mf1p33lnez

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
